### ISSUE TITLE
remote file

### ISSUE THREAD

**Issue by Perfect-Web** [widmogrod/zf2-assetic-module#119]
Hi,

Is there any way to create assets from remote files ?
For example i would include
//cdn.datatables.net/1.10.4/js/jquery.dataTables.min.js
or twitter bootstrap from cdn ?

**Comment by widmogrod** [comment]
In the module is used `Assetic\Factory\AssetFactory` which can create asset from http:
https://github.com/kriswallsmith/assetic/blob/master/src/Assetic/Factory/AssetFactory.php#L309

So short answer is possible.

**Comment by Perfect-Web** [comment]
thx
