### ISSUE TITLE
Custom image paths

### ISSUE THREAD

**Issue by jarrettj** [widmogrod/zf2-assetic-module#126]
Currently using ZF2 + bower to manage packages, such as datatables etc. When using assetic to copy files to public/assets folder, things become interesting.

The CSS for some of these bower packages expect the images and resources to be relative to where the CSS file is loaded from inside the package folder. Since we combine the CSS into one file, this will not work.

I would like to ask if this is the proper place to raise a feature request to say where the images should reside in the assetic folder?

Thanks.

**Comment by widmogrod** [comment]
I need to check if this is connected with Assetic or this module.

**Comment by Saeven** [comment]
+1, also would like to see something like this -- in my case, it's fonts that prompted checking the issues list for similar requests.  Gets messy when everything gets piled into the same directory.

**Comment by Saeven** [comment]
I made a selfish self-serving tweak here to Service.php that works.  Probably not PR-ready, because I haven't tested all cases.  Works for me to move fonts though.

https://gist.github.com/Saeven/8f0519b355359a5a3f4c

**Comment by jarrettj** [comment]
I've been forced to use .htaccess rewrite rules. Sad. Basically images referenced relative to the CSS file will have the incorrect path.

**Comment by jarrettj** [comment]
I know it's a bit late! But I found the option going through the source code.

To place a file in a particular folder I did the following:
```
'base_site_template' => array(
                        'assets' => array(
                            "$assetsDir/site_template/font/*"
                        ),
                        'options' => array(
                            'move_raw' => true,
                            'targetPath' => 'site_template',
                        )
                    ),
```

Only took me a couple of years to find targetPath. :-D

Regards.
Jarrett

**Comment by widmogrod** [comment]
Wow, awesome that you manage to find this! 
🍻
