### ISSUE TITLE
Still having issues with CacheBuster\LastModifiedStrategy

### ISSUE THREAD

**Issue by jenzer** [widmogrod/zf2-assetic-module#130]
CacheBusting described here https://github.com/widmogrod/zf2-assetic-module/blob/master/docs/tips.md does not work this way. I am getting the following error message: 

`Fatal error: Declaration of AsseticBundle\CacheBuster\LastModifiedStrategy::process() must be compatible with Assetic\Factory\Worker\WorkerInterface::process(Assetic\Asset\AssetInterface $asset, Assetic\Factory\AssetFactory $factory) in C:\...\vendor\widmogrod\zf2-assetic-module\src\AsseticBundle\CacheBuster\LastModifiedStrategy.php on line 10`

There was a github issue concerning this problem #114, which was closed on 24 Nov 2014. For me it seems not to be solved or wiki is outdated?

**Comment by widmogrod** [comment]
Which version of assetic library you have installed?
From what I can see everything is fine.

**Comment by jenzer** [comment]
I have v1.2.1 installed. 
Your composer.json is defining the version (1.*), so this must be the latest version?

**Comment by jenzer** [comment]
Migrating to your latest version 1.4.0 (release on may 2nd 2015) fixed the issue. Thanks anyway.
