### ISSUE TITLE
view helper

### ISSUE THREAD

**Issue by Perfect-Web** [widmogrod/zf2-assetic-module#132]
Zend\View\HelperPluginManager::get was unable to fetch or create an instance for asset

wasnt ` $this->asset('head_bare_js');` suppose to work ? isnt there are view helper registered ?

**Comment by widmogrod** [comment]
@Perfect-Web could you test feature branch https://github.com/widmogrod/zf2-assetic-module/issues/134
In this pull request I add view helper `asset` to ZF view helpers.

Simplest solution to use this branch is change in composer, like so:
```
"widmogrod/zf2-assetic-module": "#dev-feature/132-view-helper"
```

**Comment by Perfect-Web** [comment]
@widmogrod isnt this going to be merged soon ?

**Comment by widmogrod** [comment]
@Perfect-Web I don't have any need for this feature or module any more.
But still I will accept pull request from community.
