### ISSUE TITLE
Sass config

### ISSUE THREAD

**Issue by loispuig** [widmogrod/zf2-assetic-module#135]
Hi,
I cannot manage to make the Sass filter working.
Could you give a configuration exemple in the doc please ?

Thanks a lot, great module by the way.

**Comment by loispuig** [comment]
Ok now .scss files are compiling, but they keep their .scss extension.
Is there  any configuration option i can use so the generated files extensions are set to .css ?

**Comment by loispuig** [comment]
ok sorry i found the option in the doc...

**Comment by widmogrod** [comment]
@popovsergiy maybe you will find your answer here: https://github.com/widmogrod/zf2-assetic-module/issues/138
