### ISSUE TITLE
Prepare for ZF3, ServiceLocatorAwareInterface is deprecated

### ISSUE THREAD

**Issue by tylkomat** [widmogrod/zf2-assetic-module#143]
PHP Deprecated:  ServiceLocatorAwareInterface is deprecated and will be removed in version 3.0, along with the ServiceLocatorAwareInitializer. Please update your class **AsseticBundle\FilterManager** to remove the implementation, and start injecting your dependencies via factory instead.

PHP Deprecated:  ServiceLocatorAwareInterface is deprecated and will be removed in version 3.0, along with the ServiceLocatorAwareInitializer. Please update your class **AsseticBundle\Controller\ConsoleController** to remove the implementation, and start injecting your dependencies via factory instead.

**Comment by widmogrod** [comment]
@tylkomat thanks for noticing that.
If this feature would be useful for you, then probably will be useful for someone else in community.
Unfortunately I don't have time to do this, but **I would gladly accept your contribution to this project** :)

**Comment by Saeven** [comment]
Hey @widmogrod!  ZF3 is out now, and seems the eventManager has broken things.  You open to a PR to get it up to par?

**Comment by widmogrod** [comment]
@Saeven hi, I will gladly accept any PR that pass tests :)

**Comment by Saeven** [comment]
Thanks @widmogrod ! 
https://github.com/widmogrod/zf2-assetic-module/pull/146

Tried on a local zf3 project, seems to work well.  Tests pass.  Added zend-version to maintain ZF2 functionality.  Only very minor modifications.

**Comment by widmogrod** [comment]
@Saeven Thank you for your work!

**Comment by tylkomat** [comment]
@Saeven was already done see #147.
