### ISSUE TITLE
php public/index.php assetic build

### ISSUE THREAD

**Issue by Saeven** [widmogrod/zf2-assetic-module#155]
This command no longer seems to work.  Familiar issue? 

Seemed to start when I installed zend-mvc 3

**Comment by widmogrod** [comment]
Well I followed the steps from [how to section](https://github.com/widmogrod/zf2-assetic-module/blob/master/docs/howto.md) and everything works just fine.

Only difference is that I run command line this way:
```
vendor/bin/assetic build -vvv
```

Rather than this:
```
php public/index.php assetic build
```
