### ISSUE TITLE
PluginManager can load assets ??

### ISSUE THREAD

**Issue by jonathangreco** [widmogrod/zf2-assetic-module#162]
Hi,

First of all, thanks for this awesome module.

In my main project (years of work), I implemented a widget module. This module loads some widgets depending on an event attached to EVENT_RENDER. Those widgets are, for example, a summary of an order, a weather widget, an online help chat and so on.

My problem is about assets for one widget, I don't want to load external libraries all the time, but only those used by a widget. Assetic can do that, on modules, controllers and routes. But my Widgets are not loaded from them, but by a Plugin Manager, is Assetic able to work with that ? And how ?

If not do you have some clues to make this work ?

**Comment by widmogrod** [comment]
Hi, unfortunately this module was not designed to satisfy this requirement.
I don't see any "quick win" solution to make it work with your requirements.

IMHO your project requires bespoke solution.

**Comment by jonathangreco** [comment]
Sorry to reopen this, but your feature 134 (view hlepers) will solved my problem. Can you merge this I tested it, it worked.

**Comment by jonathangreco** [comment]
@widmogrod ping

**Comment by widmogrod** [comment]
Currently I don't have time to update outdated branch, but I will gladly accept pull request from you (and please remember about tests ;))

**Comment by jonathangreco** [comment]
Ok I will take some time to do this, can I rely on you for a litle review if needed ? @widmogrod

**Comment by widmogrod** [comment]
Yes, of course
