### ISSUE TITLE
development mode

### ISSUE THREAD

**Issue by Perfect-Web** [widmogrod/zf2-assetic-module#163]
The module doest take into consideration if you have a development mode enabled or not.
For example in my use case i have `development enable` and because of that i also have a `development.config.php`.
From what i see the module only relies on the `application.config.php` which renders the module unusable 
The best solution is to use the apigility approach and add something like this in the bin

```
$appConfig = include 'config/application.config.php';
if (file_exists('config/development.config.php')) {
    $appConfig = Zend\Stdlib\ArrayUtils::merge($appConfig, include 'config/development.config.php');
}

// Run the application!
Zend\Mvc\Application::init($appConfig)->run();

```

**Comment by widmogrod** [comment]
I don't fully understand this issue.

Module can be instructed if it's a development mode https://github.com/widmogrod/zf2-assetic-module/blob/master/docs/tips.md#development

**Comment by Perfect-Web** [comment]
@widmogrod pls refer to https://github.com/zfcampus/zf-development-mode

**Comment by widmogrod** [comment]
1. this is a solution to change dev mode above the framework level
2. it's one of many ways how to deal with environment switch (another is to have` getenv('ENV') == 'development'` check)
3. still I don't get the issue

**Comment by Perfect-Web** [comment]
its not an issues indeed :) but since is widely used, i guess is worth to have that few lines check so that it takes the env switch dont you think ?

**Comment by widmogrod** [comment]
Do you have suggestion where is should be put?

**Comment by Perfect-Web** [comment]
`bin/assetic`  replace the line 36 with what i pasted

**Comment by widmogrod** [comment]
Now I get it :) Description was not clear. Thank you for suggestion.

@Perfect-Web I will gladly accept pull request from you :)
