### ISSUE TITLE
assets by cookie

### ISSUE THREAD

**Issue by Perfect-Web** [widmogrod/zf2-assetic-module#165]
Hi guys,
Have any of you any solution or is there a feature where i can defined assets based on cookies ? 
What im asking is something similar with `routes` but to work with cookies

**Comment by widmogrod** [comment]
Basically you would need to write your own service that understands your COOKIES
And in this service use `AsseticBundle\Service::setupRendererFromOptions`

Here you have example how data is created from `controller`, `action` pair: 
https://github.com/widmogrod/zf2-assetic-module/blob/master/src/AsseticBundle/Service.php#L237
