### ISSUE TITLE
Assetic filter without constructors cannot be configured

### ISSUE THREAD

**Issue by sattes-faction** [widmogrod/zf2-assetic-module#172]
Some Assetic filters don't have constructor where the options are injected but the options are accessed via setters, e.g. the [CssCacheBustingFilter](https://github.com/kriswallsmith/assetic/blob/master/src/Assetic/Filter/CssCacheBustingFilter.php). In that case options cannot be set.

Is there any workaround for that?

**Comment by widmogrod** [comment]
Well such situation can always by solved.
ie.create new class based on `CssCacheBustingFilter` and allow set options thought constructor as you desire. 

```php
class MyCssCacheBustingFilter extend \Assetic\Filter\CssCacheBustingFilter {
  public function __construct(array $options =[]) {
     foreach($options as $method => $value) {
        $this->$method($value)
     }
  }
}
```

**Comment by sattes-faction** [comment]
Thanks, that's indeed how I did it. I just thought it might be something worth mentioning.
