### ISSUE TITLE
Using umask as chmod

### ISSUE THREAD

**Issue by bupy7** [widmogrod/zf2-assetic-module#173]
In package uses `umask` as `chmod` on [AsseticBundle\Cli\SetupCommand:42](https://github.com/widmogrod/zf2-assetic-module/blob/master/src/AsseticBundle/Cli/SetupCommand.php#L42) line.

| umask | file permission | directory permission |
|-------|-----------------|----------------------|
| 000   | rw-rw-rw-       | rwxrwxrwx            |
| 755   | ----w--w-       | ----w--w-            |
| 644   | ----w--w-       | --x-wx-wx            |
| 777   | ---------       | ---------            |

[`umask` is very dangerous function usage of which not recommended](http://php.net/manual/en/function.umask.php):

> Avoid using this function in multithreaded webservers. It is better to change the file permissions with chmod() after creating the file. Using umask() can lead to unexpected behavior of concurrently running scripts and the webserver itself because they all use the same umask. 

P.S. I used [Umask Calculator](http://www.webune.com/forums/umask-calculator.html) for above examples.

**Comment by widmogrod** [comment]
Grate job!

**Comment by widmogrod** [comment]
I have released new version `2.3.0`
