### ISSUE TITLE
Using cache busting and a CDN.

### ISSUE THREAD

**Issue by jarrettj** [widmogrod/zf2-assetic-module#176]
Hi,

Good day.

How would one deal with this situation where the requests are hitting different servers and each  server had the assets generated at different times.

Regards.
JJ

**Comment by widmogrod** [comment]
Building assets before sending them on the server is an option in your case?

**Comment by jarrettj** [comment]
Hey.

Replaced the LastModifiedStrategy with one that works for me. :)

Regards.
