### ISSUE TITLE
autocleared cache

### ISSUE THREAD

**Issue by andrconstruction** [widmogrod/zf2-assetic-module#180]
Is it a normal behavior, if I changed a style file or a js file, on a production server, after that, the assetic module kill a cache without regenerate. How to avoid this action? I want that the asstic module wait my decision or automatic regenerate. can it possible to achieve this behaviour

**Comment by widmogrod** [comment]
> can it possible to achieve this behavior

Hard to say. If you use [production config](https://github.com/widmogrod/zf2-assetic-module/blob/master/docs/tips.md#production) then, in theory, it shouldn't happen, but it's still the case then this may be `assetic-libriary issue` and with that, I cannot help.

What I may suggest to you, is to think about the process, that will not require form you editing files on a production server. You may google "how to build continuous delivery pipeline" to help you start with that.
