### ISSUE TITLE
Using yarn instead of bower.

### ISSUE THREAD

**Issue by jarrettj** [widmogrod/zf2-assetic-module#181]
Hi,

Good day.

If I use yarn instead of bower, yarn creates a symlink from the looks of it in the package.json file:
```
"postinstall": "node -e \"try { require('fs').symlinkSync(require('path').resolve('node_modules/@bower_components'), 'module/Application/assets/bower_components', 'junction') } catch (e) { }\""
```

For some reason assetic does not follow the symlink and can't find resources? Any ideas? Thanks.

Regards.
JJ

**Comment by widmogrod** [comment]
Ideas sure:
- Permissions?
- Is a symlink created after assetic executes?

Can I help you solve the problem... unfortunately without a possibility to reproduce it, I cannot do anything.

**Comment by jarrettj** [comment]
Hi,

That is fine. I changed the postinstall bit to run an rsync to the folder instead of a symlink. Works a charm. :) Thanks.

Regards.
JJ
